version: '3.7'

volumes:

  node_modules:

services:

  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    working_dir: /app
    command: ./docker/entrypoint.sh
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
