version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    working_dir: /app
    command: ./docker/entrypoint.sh
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      # We keep the Gatsby modules installed in the build phase and symlink the new ones in every run via entrypoint.
      - /app/node_modules/
