version: '3.3'

volumes:

  bundle_cache:
  redis:
  postgres:

services:

  web:
    build:
      context:    .
      dockerfile: ./docker/web.dockerfile
    labels:
      - your_project_name
    env_file:   ./.env
    command:    ./docker/scripts/start-web.sh
    tty:        true
    stdin_open: true
    depends_on:
      - postgres
      - redis
      - sidekiq
      - cable
    ports:
      - ${BIND_ON_PORT?}:${BIND_ON_PORT?}
    volumes:
      - bundle_cache:/bundle
      - .:/your_project_name

  postgres:
    labels:
      - your_project_name
    image:    postgres:11-alpine
    env_file: ./.env
    restart:  always
    ports:
      - ${POSTGRES_PORT?}:${POSTGRES_PORT?}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    build:
      context:    .
      dockerfile: ./docker/redis.dockerfile
    labels:
      - your_project_name
    env_file: ./.env
    command:  ./docker/scripts/start-redis.sh
    ports:
      - ${REDIS_PORT?}:${REDIS_PORT?}
    volumes:
      - redis:/var/lib/redis/data

  sidekiq:
    build:
      context:    .
      dockerfile: ./docker/web.dockerfile
    labels:
      - your_project_name
    env_file: ./.env
    command:  ./docker/scripts/start-sidekiq.sh
    depends_on:
      - postgres
      - redis
    volumes:
      - bundle_cache:/bundle
      - .:/your_project_name

  cable:
    build:
      context:    .
      dockerfile: ./docker/web.dockerfile
    labels:
      - your_project_name
    env_file: ./.env
    command:  ./docker/scripts/start-cable.sh
    depends_on:
      - redis
    ports:
      - ${ACTION_CABLE_PORT?}:${ACTION_CABLE_PORT?}
    volumes:
      - bundle_cache:/bundle
      - .:/your_project_name
