# frozen_string_literal: true

source "https://rubygems.org"

gem "rails",       "6.0.0"
gem "puma",        "4.3.3"
gem "pg",          "1.1.4"
gem "redis-rails", "5.0.2"
gem "sidekiq",     "5.2.7"
gem "webpacker",   "4.0.7"
