version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    working_dir: /app
    command: ./docker/entrypoint.sh
    ports:
      - '8000:8000'
    volumes:
     - .:/app
     - /app/node_modules/
